### ISSUE TITLE
Documentation needed for escaping environment variables in YAML configs

### ISSUE THREAD

**Issue by rahil-p** [rahil-p/csp-builder#1]
**Problem:**
it can be preferable to perform templating at runtime.  For example, the [NGINX Docker image](https://hub.docker.com/_/nginx) builds templates using environment variables before starting the server so that substitution values are not hardcoded into configuration files in the image.

**Suggested Solution:**
Provide documentation for escaping environment variables in the CSP configuration files, e.g.:
```yaml
Content-Security-Policy:
  connect-src:
    - $$API_URL
```
